on: 
 push:
    branches:
         -main
 pull_request:
    branches:
         -main
job:
  my_job:
    name: test srinion
    runs-on: ubuntu-22.4
  steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: .NET Restore
  # You may pin to the exact commit or the version.
  # uses: codebeltnet/dotnet-restore@1cf30dd0fdddac25bc7dcb559c6d0c310fb0d472
  uses: codebeltnet/dotnet-restore@v2.1.2
  with:
    # Optional path to the project(s) file to restore. Pass empty to restore all dependencies and tools of a solution. Supports globbing.
    projects: # default is **/*.csproj
    # Sets the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]. The default is quiet.
    level: # default is quiet
    # Whether to use the restore cache or not. Default is not to use the restore cache.
    useRestoreCache: # optional, default is false
    # Allows for a custom provided key that will be used instead of the default implementation.
    restoreCacheKey: # optional, default is 
                - name: .Net Build
  # You may pin to the exact commit or the version.
  # uses: EasyDesk/action-dotnet-build@d2c47d8701e3ea8db03dcabaacb37204fe123a22
  uses: EasyDesk/action-dotnet-build@v1.0.0
  with:
    # Additional build arguments to pass to 'dotnet build'.
    build-args: # optional
    # The build configuration to use (defaults to 'Release').
    build-configuration: # optional, default is Release
    # The path to the project or solution to build (defaults to the current directory).
    path: # optional, default is .
                      - name: .Net Unit Test
  # You may pin to the exact commit or the version.
  # uses: RachelGanonNew/Run-All-.Net-Unit-Test@bb6eb3c83b36c949e7598bdaff8198c037bd68c0
  uses: RachelGanonNew/Run-All-.Net-Unit-Test@v1.2.1
                     - name: Upload a Build Artifact
  uses: actions/upload-artifact@v4.4.3
  with:
    # Artifact name
    name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: 
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: # optional, default is warn
    # Duration after which artifact will expire in days. 0 means using default retention.
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: # optional
    # The level of compression for Zlib to be applied to the artifact archive. The value can range from 0 to 9: - 0: No compression - 1: Best speed - 6: Default compression (same as GNU Gzip) - 9: Best compression Higher levels will result in better compression, but will take longer to complete. For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.

    compression-level: # optional, default is 6
    # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.

    overwrite: # optional, default is false
    # If true, hidden files will be included in the artifact. If false, hidden files will be excluded from the artifact.

    include-hidden-files: # optional, default is false
                  
  
          
